use_frameworks!

platform :ios, '8.0'

target 'GoogleCrx_Example' do
  pod 'GoogleCrx', :path => '../'

  target 'GoogleCrx_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
